import jwt from 'jsonwebtoken'; import {z} from 'zod'; import User from '../models/User.js'; import {signAccess,signRefresh} from '../middleware/auth.js';
const schema=z.object({firstName:z.string().min(1).max(50),lastName:z.string().min(1).max(50),email:z.string().email(),phone:z.string().max(30).optional(),password:z.string().min(8).max(128),language:z.enum(['en','fr','ar','es']).optional()});
function payload(user){return {user:{id:user._id,firstName:user.firstName,lastName:user.lastName,email:user.email,role:user.role,language:user.language},accessToken:signAccess(user)}}
function cookie(res,token){res.cookie('refreshToken',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:30*24*3600*1000,path:'/api/auth'})}
export async function register(req,res){const data=schema.parse(req.body);if(await User.exists({email:data.email}))return res.status(409).json({message:'Email is already registered'});const user=await User.create(data);const refresh=signRefresh(user);user.refreshTokens=[{token:refresh}];await user.save();cookie(res,refresh);res.status(201).json(payload(user))}
export async function login(req,res){const {email,password}=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const user=await User.findOne({email}).select('+password');if(!user||!(await user.comparePassword(password)))return res.status(401).json({message:'Incorrect email or password'});const refresh=signRefresh(user);user.refreshTokens=[{token:refresh}];await user.save();cookie(res,refresh);res.json(payload(user))}
export async function refresh(req,res){try{const token=req.cookies.refreshToken;if(!token)throw Error();const {id}=jwt.verify(token,process.env.JWT_REFRESH_SECRET);const user=await User.findById(id);if(!user||!user.refreshTokens.some(t=>t.token===token))throw Error();const fresh=signRefresh(user);user.refreshTokens=[{token:fresh}];await user.save();cookie(res,fresh);res.json(payload(user))}catch{res.status(401).json({message:'Session expired'})}}
export async function logout(req,res){if(req.user){req.user.refreshTokens=[];await req.user.save()}res.clearCookie('refreshToken',{path:'/api/auth'}).status(204).end()}
export async function me(req,res){res.json({user:{id:req.user._id,firstName:req.user.firstName,lastName:req.user.lastName,email:req.user.email,role:req.user.role,language:req.user.language,favorites:req.user.favorites}})}
