import 'dotenv/config';
import {connectDatabase} from '../config/db.js';
import Restaurant from '../models/Restaurant.js';
import Offer from '../models/Offer.js';

const restaurants=[
  {name:'La Sqala',city:'Casablanca',categories:['Moroccan','Brunch','Family'],shortDescription:'Moroccan cuisine in an eighteenth-century fortress garden.',description:'A Darna partner in Casablanca’s historic medina, serving breakfast, traditional dishes, and mint tea beneath orange trees.',address:'Boulevard des Almohades, Ancienne Médina, Casablanca',location:{type:'Point',coordinates:[-7.6184,33.6009]},logo:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=256&q=80',images:['https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1400&q=85'],rating:4.6,reviewCount:890,priceLevel:2,phone:'+212522260960',website:'https://www.lasqala.com',verified:true,nfcPublicId:'DARNASQALA',openingHours:[{day:'Every day',open:'08:00',close:'23:00'}]},
  {name:'Rick’s Café',city:'Casablanca',categories:['International','Romantic','Brunch'],shortDescription:'An atmospheric piano café inspired by the classic Casablanca film.',description:'Live piano, elegant service, and a classic menu in a restored old-medina mansion.',address:'248 Boulevard Sour Jdid, Casablanca',location:{type:'Point',coordinates:[-7.6206,33.6045]},logo:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=256&q=80',images:['https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1400&q=85'],rating:4.5,reviewCount:1320,priceLevel:4,phone:'+212522274207',website:'https://www.rickscafe.ma',verified:true,nfcPublicId:'DARNARICKS',openingHours:[{day:'Every day',open:'12:00',close:'23:30'}]},
  {name:'Ito Sushi',city:'Casablanca',categories:['Sushi','Japanese','Terrace'],shortDescription:'Contemporary Japanese dining with the day’s freshest catch.',description:'A relaxed Gauthier sushi bar offering maki, nigiri, and omakase menus.',address:'12 Rue Jean Jaurès, Gauthier, Casablanca',location:{type:'Point',coordinates:[-7.6323,33.5869]},logo:'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=256&q=80',images:['https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&w=1400&q=85'],rating:4.7,reviewCount:256,priceLevel:3,phone:'+212522471188',verified:true,nfcPublicId:'DARNAITO',openingHours:[{day:'Every day',open:'12:00',close:'23:00'}]},
  {name:'Dar Zellij',city:'Marrakech',categories:['Moroccan','Romantic','Fine dining'],shortDescription:'Moroccan gastronomy served in the arches of an eighteenth-century riad.',description:'A refined medina table with candlelit courtyards and classic Moroccan hospitality.',address:'45 Derb Chtouka, Médina, Marrakech',location:{type:'Point',coordinates:[-7.9811,31.6295]},logo:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=256&q=80',images:['https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=85'],rating:4.8,reviewCount:412,priceLevel:3,phone:'+212524378902',verified:true,nfcPublicId:'DARNAZELLIJ',openingHours:[{day:'Every day',open:'18:30',close:'23:30'}]}
];
await connectDatabase();
for(const item of restaurants){const slug=item.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const restaurant=await Restaurant.findOneAndUpdate({slug},{...item,slug},{new:true,upsert:true,setDefaultsOnInsert:true});if(restaurant.name==='La Sqala')await Offer.findOneAndUpdate({restaurant:restaurant._id,title:'Lunch discovery menu',active:true},{restaurant:restaurant._id,title:'Lunch discovery menu',description:'A traditional three-course menu for weekday lunches.',discount:'20% off',active:true},{upsert:true});}
console.log(`Seeded ${restaurants.length} Darna partner restaurants`);process.exit(0);
